
const Types = {
  UserService: Symbol("UserService"),
  UserController: Symbol("UserController"),
  UserRepository: Symbol("UserRepository"),
  CreateUserService: Symbol("CreateUserService"),
  ResetPasswordService: Symbol("ResetPasswordService"),
  RestartPasswordService: Symbol("RestartPasswordService"),
  PasswordResetTokenRepository: Symbol("PasswordResetTokenRepository"),
  UpdateUserService: Symbol("UpdateUserService"),
  AuthController: Symbol("AuthController"),
  ListUserService: Symbol("ListUserService"),
  ProjetoRepository: Symbol("ProjetoRepository"),
  ProjetoController: Symbol("ProjetoController"),
  CreateProjetoService: Symbol("CreateProjetoService"),
  ListProjetoService: Symbol("ListProjetoService"),
  UpdateProjetoService: Symbol("UpdateProjetoService"),
  DeleteProjetoService: Symbol("DeleteProjetoService"),
  PowerBIController: Symbol("PowerBIController"),
  GetEmbedTokenService: Symbol("GetEmbedTokenService"),
  AutomationChatRepository: Symbol("AutomationChatRepository"),
  CreateAutomationChatService: Symbol("CreateAutomationChatService"),
  DeleteAutomationChatService: Symbol("DeleteAutomationChatService"),
  ListAutomatioChatService: Symbol("ListAutomatioChatService"),
  UpdateAutomationChatService: Symbol("UpdateAutomationChatService"),
  AutomationChatController: Symbol("AutomationChatController"),
  FormsRepository: Symbol("FormsRepository"),
  CreateFormService: Symbol("CreateFormService"),
  UpdateFormService: Symbol("UpdateFormService"),
  DeleteFormService: Symbol("DeleteFormService"),
  ListFormsService: Symbol("ListFormsService"),
  FormController: Symbol("FormController"),
  FormVersionRepository: Symbol("FormVersionRepository"),
  CreateFormVersionService: Symbol("CreateFormVersionService"),
  UpdateFormVersionService: Symbol("UpdateFormVersionService"),
  DeleteFormVersionService: Symbol("DeleteFormVersionService"),
  ListFormVersionsService: Symbol("ListFormVersionsService"),
  FormVersionController: Symbol("FormVersionController"),
  PublicFormReadRepository: Symbol("PublicFormReadRepository"),
  PublicFormReadService: Symbol("PublicFormReadService"),
  PublicFormController: Symbol("PublicFormController"),
  FormFieldRepository: Symbol("FormFieldRepository"),
  CreateFormFieldService: Symbol("CreateFormFieldService"),
  UpdateFormFieldService: Symbol("UpdateFormFieldService"),
  DeleteFormFieldService: Symbol("DeleteFormFieldService"),
  ListFormFieldsService: Symbol("ListFormFieldsService"),
  FormFieldController: Symbol("FormFieldController"),
  FormResponseRepository: Symbol("FormResponseRepository"),
  CreateFormResponseService: Symbol("CreateFormResponseService"),
  UpdateFormResponseService: Symbol("UpdateFormResponseService"),
  ListFormResponsesService: Symbol("ListFormResponsesService"),
  DeleteFormResponseService: Symbol("DeleteFormResponseService"),
  FormResponseController: Symbol("FormResponseController"),
  FormResponseMetricsService: Symbol("FormResponseMetricsService"),
  FormResponseMetricsController: Symbol("FormResponseMetricsController"),
};

export default Types;
